language: python
python:
 - "3.4"
 
before_intall:
  - git config --global user.email "glauber.vila.verde@gmail.com"
  - git config --global user.name "glaubervila"
  - git config --global push.default simple
  
install:
  - pip install coverage
  
script:
  - echo "Teste Push File to Git Hub" > NewFile.txt
  
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  
  - git branch
  
  - git status
  - git add -A
  - git status  
  - git commit -m 'Travis build'
  
  - git remote -v
  - git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git
  - git push
  - echo "Parece que funcionou"
